export const GET_WEATHER_DATA = "GET_WEATHER_DATA";
export const GET_WEATHER_DATA_SUCCESS = "GET_WEATHER_DATA_SUCCESS";

export const GET_TODOLIST_DATA = "GET_TODOLIST_DATA";
export const GET_TODOLIST_DATA_SUCCESS = "GET_TODOLIST_DATA_SUCCESS";

export const POST_TODOLIST_DATA = "POST_TODOLIST_DATA";
export const POST_TODOLIST_DATA_SUCCESS = "POST_TODOLIST_DATA_SUCCESS";

export const DELETE_TODOLIST_DATA = "DELETE_TODOLIST_DATA"
export const DELETE_TODOLIST_DATA_SUCCESS = "DELETE_TODOLIST_DATA_SUCCESS"

export const PATCH_TODOLIST_DATA = "PATCH_TODOLIST_DATA"
export const PATCH_TODOLIST_DATA_SUCCESS = "PATCH_TODOLIST_DATA_SUCCESS"